/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaReporteStock.java
 *
 * Created on 20/10/2011, 10:30:51
 */

package InterfacesGraficas.Reportes;

import InterfacesGraficas.DTOStockProducto;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juampa
 */
public class PantallaReporteStock extends javax.swing.JFrame {

    List<DTOStockProducto> stocks = new ArrayList();

    public PantallaReporteStock() {
        initComponents();
    }
    
    public PantallaReporteStock(List<DTOStockProducto> dtos, Date fecha) {
        initComponents();
        stocks = dtos;
        jLabelDia.setText(Integer.toString(fecha.getDay()));
        jLabelAño.setText(Integer.toString(fecha.getYear() + 1900));
        jLabelMes.setText(cargarMes(fecha));
        CargarTabla();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStocks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelMes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelAño = new javax.swing.JLabel();
        jLabelDia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado");
        setResizable(false);

        jTableStocks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Stock"
            }
        ));
        jScrollPane1.setViewportView(jTableStocks);

        jLabel1.setText("Reporte correspondiente al día");

        jLabelMes.setText("Septiembre");

        jLabel2.setText("del");

        jLabelAño.setText("año");

        jLabelDia.setText("31");

        jLabel4.setText("de");

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAño)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, Short.MAX_VALUE)
                                .addComponent(jButtonCerrar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelDia)
                    .addComponent(jLabel4)
                    .addComponent(jLabelMes)
                    .addComponent(jLabel2)
                    .addComponent(jLabelAño))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

//Muestra todos los clientes en tabla
    public  void CargarTabla() {
        try {

            Object[][] datos = null;
            
            datos = new Object[stocks.size()][3];
            for (int i = 0; i < stocks.size(); i++) {
                datos[i][0] = stocks.get(i).getNombre();
                datos[i][1] = stocks.get(i).getCodigo();
                datos[i][2] = stocks.get(i).getStock();

            }
            
            String[] columnNames = {"Código","Producto", "Stock"};
            jTableStocks.setModel(new DefaultTableModel(datos, columnNames) {

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            });

        } catch (NullPointerException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAño;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStocks;
    // End of variables declaration//GEN-END:variables

    private String cargarMes(Date fecha) {
        String mes = "Enero";
        if(fecha.getMonth() == 0){
            mes = "Enero";
        }else if (fecha.getMonth() == 1){
            mes = "Febrero";
        }else if (fecha.getMonth() == 2){
            mes = "Marzo";
        }else if (fecha.getMonth() == 3){
            mes = "Abril";
        }else if (fecha.getMonth() == 4){
            mes = "Mayo";
        }else if (fecha.getMonth() == 5){
            mes = "Junio";
        }else if (fecha.getMonth() == 6){
            mes = "Julio";
        }else if (fecha.getMonth() == 7){
            mes = "Agosto";
        }else if (fecha.getMonth() == 8){
            mes = "Septiembre";
        }else if (fecha.getMonth() == 9){
            mes = "Octubre";
        }else if (fecha.getMonth() == 10){
            mes = "Noviembre";
        }else if (fecha.getMonth() == 11){
            mes = "Diciembre";
        }
        return mes;
    }

}
