/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaEvolucionComprasClienteRespectoAUnProducto.java
 *
 * Created on 14/05/2011, 17:11:35
 */

package InterfacesGraficas.Reportes;

import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author rustu
 */
public class PantallaEvolucionComprasClienteRespectoAUnProducto extends javax.swing.JFrame {
    private ControladorEvolucionComprasClienteRespectoAUnProducto controlador;
    /** Creates new form PantallaEvolucionComprasClienteRespectoAUnProducto */
    public PantallaEvolucionComprasClienteRespectoAUnProducto(ControladorEvolucionComprasClienteRespectoAUnProducto controlador) {
        initComponents();
        String[] meses = {"Enero", "Febrero", "Marzo" , "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre","Octubre", "Noviembre", "Diciembre"};
        mesInicioComboBox.setModel(new DefaultComboBoxModel(meses));
        mesFinComboBox.setModel(new DefaultComboBoxModel(meses));
        this.controlador = controlador;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscar = new javax.swing.JButton();
        limpiarPantalla = new javax.swing.JButton();
        producto = new javax.swing.JPanel();
        codigoProductoLabel = new javax.swing.JLabel();
        codigoProducto = new javax.swing.JTextField();
        nombreProductoLabel = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        buscarProducto = new javax.swing.JButton();
        cliente = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        numeroCliente = new javax.swing.JTextField();
        cuitLabel = new javax.swing.JLabel();
        cuitCliente = new javax.swing.JTextField();
        buscarPorNombreCliente = new javax.swing.JButton();
        buscarPorNumeroCliente = new javax.swing.JButton();
        buscarPorCuitCliente = new javax.swing.JButton();
        clienteSeleccionado = new javax.swing.JTextField();
        clienteSeleccionadoLabel = new javax.swing.JLabel();
        fechas = new javax.swing.JPanel();
        fechaInicioLabel = new javax.swing.JLabel();
        mesInicioLabel = new javax.swing.JLabel();
        mesInicioComboBox = new javax.swing.JComboBox();
        anioInicio = new javax.swing.JTextField();
        anioFinLabel = new javax.swing.JLabel();
        fechaFinLabel = new javax.swing.JLabel();
        mesFinLabel = new javax.swing.JLabel();
        mesFinComboBox = new javax.swing.JComboBox();
        anioFin = new javax.swing.JTextField();
        anioInicioLabel = new javax.swing.JLabel();
        mostrarMesesEnCero = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Evolucion venta de producto respecto a un cliente");
        setResizable(false);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarKeyPressed(evt);
            }
        });

        limpiarPantalla.setText("Limpiar Pantalla");
        limpiarPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarPantallaActionPerformed(evt);
            }
        });
        limpiarPantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                limpiarPantallaKeyPressed(evt);
            }
        });

        producto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto"));

        codigoProductoLabel.setText("Código Producto");

        codigoProducto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProductoActionPerformed(evt);
            }
        });

        nombreProductoLabel.setText("Nombre Producto");

        nombreProducto.setEnabled(false);
        nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoActionPerformed(evt);
            }
        });

        buscarProducto.setText("Buscar Producto");
        buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductoActionPerformed(evt);
            }
        });
        buscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarProductoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout productoLayout = new javax.swing.GroupLayout(producto);
        producto.setLayout(productoLayout);
        productoLayout.setHorizontalGroup(
            productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(productoLayout.createSequentialGroup()
                        .addComponent(codigoProductoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(codigoProducto)
                        .addGap(18, 18, 18)
                        .addComponent(buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productoLayout.createSequentialGroup()
                        .addComponent(nombreProductoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productoLayout.setVerticalGroup(
            productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productoLayout.createSequentialGroup()
                .addGroup(productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoProductoLabel)
                    .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProductoLabel)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cliente"));

        nombreLabel.setText("Nombre");

        numeroLabel.setText("Número");

        nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteActionPerformed(evt);
            }
        });

        numeroCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numeroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroClienteActionPerformed(evt);
            }
        });

        cuitLabel.setText("CUIT");

        cuitCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cuitCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuitClienteActionPerformed(evt);
            }
        });
        cuitCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cuitClienteFocusGained(evt);
            }
        });

        buscarPorNombreCliente.setText("Buscar");
        buscarPorNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorNombreClienteActionPerformed(evt);
            }
        });
        buscarPorNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarPorNombreClienteKeyPressed(evt);
            }
        });

        buscarPorNumeroCliente.setText("Buscar");
        buscarPorNumeroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorNumeroClienteActionPerformed(evt);
            }
        });
        buscarPorNumeroCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarPorNumeroClienteKeyPressed(evt);
            }
        });

        buscarPorCuitCliente.setText("Buscar");
        buscarPorCuitCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorCuitClienteActionPerformed(evt);
            }
        });
        buscarPorCuitCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarPorCuitClienteKeyPressed(evt);
            }
        });

        clienteSeleccionado.setEnabled(false);

        clienteSeleccionadoLabel.setText("Cliente Seleccionado");

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente);
        cliente.setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clienteLayout.createSequentialGroup()
                                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroLabel)
                                    .addComponent(cuitLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cuitCliente)
                                    .addComponent(nombreCliente)
                                    .addComponent(numeroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarPorNombreCliente)
                            .addComponent(buscarPorNumeroCliente)
                            .addComponent(buscarPorCuitCliente)))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addComponent(clienteSeleccionadoLabel)
                        .addGap(3, 3, 3)
                        .addComponent(clienteSeleccionado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorNombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorNumeroCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitLabel)
                    .addComponent(cuitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorCuitCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteSeleccionadoLabel)
                    .addComponent(clienteSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fechas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fechas"));

        fechaInicioLabel.setText("Fecha inicio");

        mesInicioLabel.setText("Mes");

        mesInicioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mesInicioComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mesInicioComboBoxKeyPressed(evt);
            }
        });

        anioInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        anioInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioInicioActionPerformed(evt);
            }
        });

        anioFinLabel.setText("Año");

        fechaFinLabel.setText("Fecha fin");

        mesFinLabel.setText("Mes");

        mesFinComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mesFinComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mesFinComboBoxKeyPressed(evt);
            }
        });

        anioFin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        anioFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioFinActionPerformed(evt);
            }
        });

        anioInicioLabel.setText("Año");

        javax.swing.GroupLayout fechasLayout = new javax.swing.GroupLayout(fechas);
        fechas.setLayout(fechasLayout);
        fechasLayout.setHorizontalGroup(
            fechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaInicioLabel)
                    .addGroup(fechasLayout.createSequentialGroup()
                        .addGroup(fechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fechasLayout.createSequentialGroup()
                                    .addComponent(mesFinLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesFinComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fechasLayout.createSequentialGroup()
                                    .addComponent(mesInicioLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesInicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fechaFinLabel))
                        .addGap(18, 18, 18)
                        .addGroup(fechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fechasLayout.createSequentialGroup()
                                .addComponent(anioInicioLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anioInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                            .addGroup(fechasLayout.createSequentialGroup()
                                .addComponent(anioFinLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anioFin, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        fechasLayout.setVerticalGroup(
            fechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechasLayout.createSequentialGroup()
                .addComponent(fechaInicioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesInicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesInicioLabel)
                    .addComponent(anioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioInicioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaFinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesFinLabel)
                    .addComponent(mesFinComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioFinLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mostrarMesesEnCero.setText("Mostrar meses que estén en cero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiarPantalla)
                        .addGap(18, 18, 18)
                        .addComponent(mostrarMesesEnCero)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(limpiarPantalla)
                    .addComponent(mostrarMesesEnCero))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        controlador.buscarEvolucion();
    }//GEN-LAST:event_buscarActionPerformed

    private void codigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProductoActionPerformed
        controlador.buscarProducto();
    }//GEN-LAST:event_codigoProductoActionPerformed

    private void nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoActionPerformed
        getMesInicioComboBox().requestFocus();
    }//GEN-LAST:event_nombreProductoActionPerformed

    private void anioInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioInicioActionPerformed
        getMesFinComboBox().requestFocus();
    }//GEN-LAST:event_anioInicioActionPerformed

    private void anioFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioFinActionPerformed
        getBuscar().requestFocus();
    }//GEN-LAST:event_anioFinActionPerformed

    private void nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteActionPerformed
        controlador.buscarClientePorNombre(getNombreCliente().getText());
    }//GEN-LAST:event_nombreClienteActionPerformed

    private void numeroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroClienteActionPerformed
        controlador.buscarClientePorNumero(getNumeroCliente().getText());
    }//GEN-LAST:event_numeroClienteActionPerformed

    private void cuitClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuitClienteActionPerformed
        controlador.buscarClientePorCuit(getCuitCliente().getText());
    }//GEN-LAST:event_cuitClienteActionPerformed

    private void mesInicioComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesInicioComboBoxKeyPressed
        if (evt.getKeyCode()==10)
            {
                getAnioInicio().requestFocus();
            }


    }//GEN-LAST:event_mesInicioComboBoxKeyPressed

    private void mesFinComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesFinComboBoxKeyPressed
        if (evt.getKeyCode()==10)
            {
                getAnioFin().requestFocus();
            }

    }//GEN-LAST:event_mesFinComboBoxKeyPressed

    private void cuitClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cuitClienteFocusGained
        controlador.colocarCuitEnFormatoParaEditar();
    }//GEN-LAST:event_cuitClienteFocusGained

    private void limpiarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarPantallaActionPerformed
        controlador.limpiarPantalla();
    }//GEN-LAST:event_limpiarPantallaActionPerformed

    private void buscarPorNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorNombreClienteActionPerformed
        controlador.buscarClientePorNombre(getNombreCliente().getText());
    }//GEN-LAST:event_buscarPorNombreClienteActionPerformed

    private void buscarPorNumeroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorNumeroClienteActionPerformed
        controlador.buscarClientePorNumero(getNumeroCliente().getText());

    }//GEN-LAST:event_buscarPorNumeroClienteActionPerformed

    private void buscarPorCuitClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorCuitClienteActionPerformed
       controlador.buscarClientePorCuit(getCuitCliente().getText());
    }//GEN-LAST:event_buscarPorCuitClienteActionPerformed

    private void buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoActionPerformed
        controlador.buscarProducto();
    }//GEN-LAST:event_buscarProductoActionPerformed
//REVISAR DESDE ACA BOTONES

    private void buscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProductoKeyPressed
        if (evt.getKeyCode()==10)
            {
                controlador.buscarProducto();
            }

    }//GEN-LAST:event_buscarProductoKeyPressed

    private void buscarPorNombreClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarPorNombreClienteKeyPressed
       if (evt.getKeyCode()==10)
            {
                controlador.buscarClientePorNombre(getNombreCliente().getText());
            }
    }//GEN-LAST:event_buscarPorNombreClienteKeyPressed

    private void buscarPorNumeroClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarPorNumeroClienteKeyPressed
        if (evt.getKeyCode()==10)
            {
                controlador.buscarClientePorNumero(getNumeroCliente().getText());
            }
    }//GEN-LAST:event_buscarPorNumeroClienteKeyPressed

    private void buscarPorCuitClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarPorCuitClienteKeyPressed
       if (evt.getKeyCode()==10)
            {
               controlador.buscarClientePorCuit(getCuitCliente().getText());
            }
    }//GEN-LAST:event_buscarPorCuitClienteKeyPressed

    private void buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyPressed
        if (evt.getKeyCode()==10)
            {
               controlador.buscarEvolucion();
            }
    }//GEN-LAST:event_buscarKeyPressed

    private void limpiarPantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_limpiarPantallaKeyPressed
       if (evt.getKeyCode()==10)
            {
                 controlador.limpiarPantalla();
            }
    }//GEN-LAST:event_limpiarPantallaKeyPressed
                                        

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaEvolucionComprasClienteRespectoAUnProducto().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioFin;
    private javax.swing.JLabel anioFinLabel;
    private javax.swing.JTextField anioInicio;
    private javax.swing.JLabel anioInicioLabel;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscarPorCuitCliente;
    private javax.swing.JButton buscarPorNombreCliente;
    private javax.swing.JButton buscarPorNumeroCliente;
    private javax.swing.JButton buscarProducto;
    private javax.swing.JPanel cliente;
    private javax.swing.JTextField clienteSeleccionado;
    private javax.swing.JLabel clienteSeleccionadoLabel;
    private javax.swing.JTextField codigoProducto;
    private javax.swing.JLabel codigoProductoLabel;
    private javax.swing.JTextField cuitCliente;
    private javax.swing.JLabel cuitLabel;
    private javax.swing.JLabel fechaFinLabel;
    private javax.swing.JLabel fechaInicioLabel;
    private javax.swing.JPanel fechas;
    private javax.swing.JButton limpiarPantalla;
    private javax.swing.JComboBox mesFinComboBox;
    private javax.swing.JLabel mesFinLabel;
    private javax.swing.JComboBox mesInicioComboBox;
    private javax.swing.JLabel mesInicioLabel;
    private javax.swing.JCheckBox mostrarMesesEnCero;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JLabel nombreProductoLabel;
    private javax.swing.JTextField numeroCliente;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JPanel producto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the anioFin
     */
    public javax.swing.JTextField getAnioFin() {
        return anioFin;
    }

    /**
     * @param anioFin the anioFin to set
     */
    public void setAnioFin(javax.swing.JTextField anioFin) {
        this.anioFin = anioFin;
    }

    /**
     * @return the anioFinLabel
     */
    public javax.swing.JLabel getAnioFinLabel() {
        return anioFinLabel;
    }

    /**
     * @param anioFinLabel the anioFinLabel to set
     */
    public void setAnioFinLabel(javax.swing.JLabel anioFinLabel) {
        this.anioFinLabel = anioFinLabel;
    }

    /**
     * @return the anioInicio
     */
    public javax.swing.JTextField getAnioInicio() {
        return anioInicio;
    }

    /**
     * @param anioInicio the anioInicio to set
     */
    public void setAnioInicio(javax.swing.JTextField anioInicio) {
        this.anioInicio = anioInicio;
    }

    /**
     * @return the anioInicioLabel
     */
    public javax.swing.JLabel getAnioInicioLabel() {
        return anioInicioLabel;
    }

    /**
     * @param anioInicioLabel the anioInicioLabel to set
     */
    public void setAnioInicioLabel(javax.swing.JLabel anioInicioLabel) {
        this.anioInicioLabel = anioInicioLabel;
    }

    /**
     * @return the buscar
     */
    public javax.swing.JButton getBuscar() {
        return buscar;
    }

    /**
     * @param buscar the buscar to set
     */
    public void setBuscar(javax.swing.JButton buscar) {
        this.buscar = buscar;
    }

    /**
     * @return the buscarPorCuitCliente
     */
    public javax.swing.JButton getBuscarPorCuitCliente() {
        return buscarPorCuitCliente;
    }

    /**
     * @param buscarPorCuitCliente the buscarPorCuitCliente to set
     */
    public void setBuscarPorCuitCliente(javax.swing.JButton buscarPorCuitCliente) {
        this.buscarPorCuitCliente = buscarPorCuitCliente;
    }

    /**
     * @return the buscarPorNombreCliente
     */
    public javax.swing.JButton getBuscarPorNombreCliente() {
        return buscarPorNombreCliente;
    }

    /**
     * @param buscarPorNombreCliente the buscarPorNombreCliente to set
     */
    public void setBuscarPorNombreCliente(javax.swing.JButton buscarPorNombreCliente) {
        this.buscarPorNombreCliente = buscarPorNombreCliente;
    }

    /**
     * @return the buscarPorNumeroCliente
     */
    public javax.swing.JButton getBuscarPorNumeroCliente() {
        return buscarPorNumeroCliente;
    }

    /**
     * @param buscarPorNumeroCliente the buscarPorNumeroCliente to set
     */
    public void setBuscarPorNumeroCliente(javax.swing.JButton buscarPorNumeroCliente) {
        this.buscarPorNumeroCliente = buscarPorNumeroCliente;
    }

    /**
     * @return the buscarProducto
     */
    public javax.swing.JButton getBuscarProducto() {
        return buscarProducto;
    }

    /**
     * @param buscarProducto the buscarProducto to set
     */
    public void setBuscarProducto(javax.swing.JButton buscarProducto) {
        this.buscarProducto = buscarProducto;
    }

    /**
     * @return the cliente
     */
    public javax.swing.JPanel getCliente() {
        return cliente;
    }

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(javax.swing.JPanel cliente) {
        this.cliente = cliente;
    }

    /**
     * @return the clienteSeleccionado
     */
    public javax.swing.JTextField getClienteSeleccionado() {
        return clienteSeleccionado;
    }

    /**
     * @param clienteSeleccionado the clienteSeleccionado to set
     */
    public void setClienteSeleccionado(javax.swing.JTextField clienteSeleccionado) {
        this.clienteSeleccionado = clienteSeleccionado;
    }

    /**
     * @return the clienteSeleccionadoLabel
     */
    public javax.swing.JLabel getClienteSeleccionadoLabel() {
        return clienteSeleccionadoLabel;
    }

    /**
     * @param clienteSeleccionadoLabel the clienteSeleccionadoLabel to set
     */
    public void setClienteSeleccionadoLabel(javax.swing.JLabel clienteSeleccionadoLabel) {
        this.clienteSeleccionadoLabel = clienteSeleccionadoLabel;
    }

    /**
     * @return the codigoProducto
     */
    public javax.swing.JTextField getCodigoProducto() {
        return codigoProducto;
    }

    /**
     * @param codigoProducto the codigoProducto to set
     */
    public void setCodigoProducto(javax.swing.JTextField codigoProducto) {
        this.codigoProducto = codigoProducto;
    }

    /**
     * @return the codigoProductoLabel
     */
    public javax.swing.JLabel getCodigoProductoLabel() {
        return codigoProductoLabel;
    }

    /**
     * @param codigoProductoLabel the codigoProductoLabel to set
     */
    public void setCodigoProductoLabel(javax.swing.JLabel codigoProductoLabel) {
        this.codigoProductoLabel = codigoProductoLabel;
    }

    /**
     * @return the cuitCliente
     */
    public javax.swing.JTextField getCuitCliente() {
        return cuitCliente;
    }

    /**
     * @param cuitCliente the cuitCliente to set
     */
    public void setCuitCliente(javax.swing.JTextField cuitCliente) {
        this.cuitCliente = cuitCliente;
    }

    /**
     * @return the cuitLabel
     */
    public javax.swing.JLabel getCuitLabel() {
        return cuitLabel;
    }

    /**
     * @param cuitLabel the cuitLabel to set
     */
    public void setCuitLabel(javax.swing.JLabel cuitLabel) {
        this.cuitLabel = cuitLabel;
    }

    /**
     * @return the fechaFinLabel
     */
    public javax.swing.JLabel getFechaFinLabel() {
        return fechaFinLabel;
    }

    /**
     * @param fechaFinLabel the fechaFinLabel to set
     */
    public void setFechaFinLabel(javax.swing.JLabel fechaFinLabel) {
        this.fechaFinLabel = fechaFinLabel;
    }

    /**
     * @return the fechaInicioLabel
     */
    public javax.swing.JLabel getFechaInicioLabel() {
        return fechaInicioLabel;
    }

    /**
     * @param fechaInicioLabel the fechaInicioLabel to set
     */
    public void setFechaInicioLabel(javax.swing.JLabel fechaInicioLabel) {
        this.fechaInicioLabel = fechaInicioLabel;
    }

    /**
     * @return the fechas
     */
    public javax.swing.JPanel getFechas() {
        return fechas;
    }

    /**
     * @param fechas the fechas to set
     */
    public void setFechas(javax.swing.JPanel fechas) {
        this.fechas = fechas;
    }

    /**
     * @return the limpiarPantalla
     */
    public javax.swing.JButton getLimpiarPantalla() {
        return limpiarPantalla;
    }

    /**
     * @param limpiarPantalla the limpiarPantalla to set
     */
    public void setLimpiarPantalla(javax.swing.JButton limpiarPantalla) {
        this.limpiarPantalla = limpiarPantalla;
    }

    /**
     * @return the mesFinComboBox
     */
    public javax.swing.JComboBox getMesFinComboBox() {
        return mesFinComboBox;
    }

    /**
     * @param mesFinComboBox the mesFinComboBox to set
     */
    public void setMesFinComboBox(javax.swing.JComboBox mesFinComboBox) {
        this.mesFinComboBox = mesFinComboBox;
    }

    /**
     * @return the mesFinLabel
     */
    public javax.swing.JLabel getMesFinLabel() {
        return mesFinLabel;
    }

    /**
     * @param mesFinLabel the mesFinLabel to set
     */
    public void setMesFinLabel(javax.swing.JLabel mesFinLabel) {
        this.mesFinLabel = mesFinLabel;
    }

    /**
     * @return the mesInicioComboBox
     */
    public javax.swing.JComboBox getMesInicioComboBox() {
        return mesInicioComboBox;
    }

    /**
     * @param mesInicioComboBox the mesInicioComboBox to set
     */
    public void setMesInicioComboBox(javax.swing.JComboBox mesInicioComboBox) {
        this.mesInicioComboBox = mesInicioComboBox;
    }

    /**
     * @return the mesInicioLabel
     */
    public javax.swing.JLabel getMesInicioLabel() {
        return mesInicioLabel;
    }

    /**
     * @param mesInicioLabel the mesInicioLabel to set
     */
    public void setMesInicioLabel(javax.swing.JLabel mesInicioLabel) {
        this.mesInicioLabel = mesInicioLabel;
    }

    /**
     * @return the mostrarMesesEnCero
     */
    public javax.swing.JCheckBox getMostrarMesesEnCero() {
        return mostrarMesesEnCero;
    }

    /**
     * @param mostrarMesesEnCero the mostrarMesesEnCero to set
     */
    public void setMostrarMesesEnCero(javax.swing.JCheckBox mostrarMesesEnCero) {
        this.mostrarMesesEnCero = mostrarMesesEnCero;
    }

    /**
     * @return the nombreCliente
     */
    public javax.swing.JTextField getNombreCliente() {
        return nombreCliente;
    }

    /**
     * @param nombreCliente the nombreCliente to set
     */
    public void setNombreCliente(javax.swing.JTextField nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    /**
     * @return the nombreLabel
     */
    public javax.swing.JLabel getNombreLabel() {
        return nombreLabel;
    }

    /**
     * @param nombreLabel the nombreLabel to set
     */
    public void setNombreLabel(javax.swing.JLabel nombreLabel) {
        this.nombreLabel = nombreLabel;
    }

    /**
     * @return the nombreProducto
     */
    public javax.swing.JTextField getNombreProducto() {
        return nombreProducto;
    }

    /**
     * @param nombreProducto the nombreProducto to set
     */
    public void setNombreProducto(javax.swing.JTextField nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    /**
     * @return the nombreProductoLabel
     */
    public javax.swing.JLabel getNombreProductoLabel() {
        return nombreProductoLabel;
    }

    /**
     * @param nombreProductoLabel the nombreProductoLabel to set
     */
    public void setNombreProductoLabel(javax.swing.JLabel nombreProductoLabel) {
        this.nombreProductoLabel = nombreProductoLabel;
    }

    /**
     * @return the numeroCliente
     */
    public javax.swing.JTextField getNumeroCliente() {
        return numeroCliente;
    }

    /**
     * @param numeroCliente the numeroCliente to set
     */
    public void setNumeroCliente(javax.swing.JTextField numeroCliente) {
        this.numeroCliente = numeroCliente;
    }

    /**
     * @return the numeroLabel
     */
    public javax.swing.JLabel getNumeroLabel() {
        return numeroLabel;
    }

    /**
     * @param numeroLabel the numeroLabel to set
     */
    public void setNumeroLabel(javax.swing.JLabel numeroLabel) {
        this.numeroLabel = numeroLabel;
    }

    /**
     * @return the producto
     */
    public javax.swing.JPanel getProducto() {
        return producto;
    }

    /**
     * @param producto the producto to set
     */
    public void setProducto(javax.swing.JPanel producto) {
        this.producto = producto;
    }

    
}
