/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaEvolucionComprasClienteRespectoAUnProducto.java
 *
 * Created on 14/05/2011, 17:11:35
 */

package InterfacesGraficas.Reportes;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author rustu
 */
public class PantallaEvolucionComprasClienteRespectoAUnProducto extends javax.swing.JFrame {
    private ControladorEvolucionComprasClienteRespectoAUnProducto controlador;
    /** Creates new form PantallaEvolucionComprasClienteRespectoAUnProducto */
    public PantallaEvolucionComprasClienteRespectoAUnProducto(ControladorEvolucionComprasClienteRespectoAUnProducto controlador) {
        initComponents();
        String[] meses = {"Enero", "Febrero", "Marzo" , "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre","Octubre", "Noviembre", "Diciembre"};
        mesInicioComboBox.setModel(new DefaultComboBoxModel(meses));
        mesFinComboBox.setModel(new DefaultComboBoxModel(meses));
        this.controlador = controlador;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoProductoLabel = new javax.swing.JLabel();
        codigoProducto = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        fechaInicioLabel = new javax.swing.JLabel();
        fechaFinLabel = new javax.swing.JLabel();
        mesInicioComboBox = new javax.swing.JComboBox();
        mesFinComboBox = new javax.swing.JComboBox();
        anioInicio = new javax.swing.JTextField();
        anioFin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Evolucion venta de producto");

        codigoProductoLabel.setText("Código Producto");

        aceptar.setText("Buscar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        fechaInicioLabel.setText("Fecha inicio");

        fechaFinLabel.setText("Fecha fin");

        mesInicioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mesFinComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        anioInicio.setText("Año");

        anioFin.setText("Año");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(codigoProductoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(codigoProducto))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fechaInicioLabel)
                                .addComponent(fechaFinLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mesFinComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mesInicioComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 103, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(anioInicio)
                                .addComponent(anioFin, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))))
                    .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoProductoLabel)
                    .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaInicioLabel)
                    .addComponent(mesInicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaFinLabel)
                    .addComponent(mesFinComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        controlador.buscarProducto();
    }//GEN-LAST:event_aceptarActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaEvolucionComprasClienteRespectoAUnProducto().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField anioFin;
    private javax.swing.JTextField anioInicio;
    private javax.swing.JTextField codigoProducto;
    private javax.swing.JLabel codigoProductoLabel;
    private javax.swing.JLabel fechaFinLabel;
    private javax.swing.JLabel fechaInicioLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox mesFinComboBox;
    private javax.swing.JComboBox mesInicioComboBox;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the aceptar
     */
    public javax.swing.JButton getAceptar() {
        return aceptar;
    }

    /**
     * @param aceptar the aceptar to set
     */
    public void setAceptar(javax.swing.JButton aceptar) {
        this.aceptar = aceptar;
    }

    /**
     * @return the codigoProducto
     */
    public javax.swing.JTextField getCodigoProducto() {
        return codigoProducto;
    }

    /**
     * @param codigoProducto the codigoProducto to set
     */
    public void setCodigoProducto(javax.swing.JTextField codigoProducto) {
        this.codigoProducto = codigoProducto;
    }

    /**
     * @return the codigoProductoLabel
     */
    public javax.swing.JLabel getCodigoProductoLabel() {
        return codigoProductoLabel;
    }

    /**
     * @param codigoProductoLabel the codigoProductoLabel to set
     */
    public void setCodigoProductoLabel(javax.swing.JLabel codigoProductoLabel) {
        this.codigoProductoLabel = codigoProductoLabel;
    }

    /**
     * @return the anioFin
     */
    public javax.swing.JTextField getAnioFin() {
        return anioFin;
    }

    /**
     * @param anioFin the anioFin to set
     */
    public void setAnioFin(javax.swing.JTextField anioFin) {
        this.anioFin = anioFin;
    }

    /**
     * @return the anioInicio
     */
    public javax.swing.JTextField getAnioInicio() {
        return anioInicio;
    }

    /**
     * @param anioInicio the anioInicio to set
     */
    public void setAnioInicio(javax.swing.JTextField anioInicio) {
        this.anioInicio = anioInicio;
    }

    /**
     * @return the mesFinComboBox
     */
    public javax.swing.JComboBox getMesFinComboBox() {
        return mesFinComboBox;
    }

    /**
     * @param mesFinComboBox the mesFinComboBox to set
     */
    public void setMesFinComboBox(javax.swing.JComboBox mesFinComboBox) {
        this.mesFinComboBox = mesFinComboBox;
    }

    /**
     * @return the mesInicioComboBox
     */
    public javax.swing.JComboBox getMesInicioComboBox() {
        return mesInicioComboBox;
    }

    /**
     * @param mesInicioComboBox the mesInicioComboBox to set
     */
    public void setMesInicioComboBox(javax.swing.JComboBox mesInicioComboBox) {
        this.mesInicioComboBox = mesInicioComboBox;
    }

}
